version: '3.8'


networks:
  net-client:
  net-api:


volumes:
  db:
    name: db


services:
  
  client:
    container_name: client
    restart: unless-stopped
    build:
      context: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - net-client
    depends_on:
      - api

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    env_file:
      - api/.env
    networks:
      - net-client
      - net-api
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    networks:
      - net-api
    ports:
      - "5432"
    env_file:
      - .env 
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer:4-standalone
    restart: unless-stopped
    networks:
      - net-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
